@setup_workload begin
    # Putting some things in `setup` can reduce the size of the
    # precompile file and potentially make loading faster.
    nothing
    using LinearAlgebra: opnorm
    using IntegerExtensions
    gates_r1024 = "TSHTHTHTHTSHTSHTSHTSHTSHTSHTHTSHTSHTSHTSHTHTHTHTSHTSHTSHTHTHTHTHTSHTSHTHTSHTSHTSHTHTHTHTHTHTHTHTSHTSHTSHTSHTHTHTHTSHTHTHTSHTSHTSHTSHTHTHTSHTHTHTHTHTHTSHTHTSHTHTHTSHTSHTSHTSHTHTHTHTSHTSHTHTSHTSHTSHTHTSHTHTSHTSHTHTHTHTSHTHTHTHTSHTSHTSHTSHTSHTHTSHTSHTSHTSHTSHTHTSHTSHTHTSHTHTSHTHTHTSHTHTHTSHTSHTSHTHTSHTSHTHTHTHTSHTHTHTSHTSHTHTHTSHTHTHTSHTHTHTHTSHTHTHTHTSHTHTSHTSHTHTSHTSHTHTSHTHTSHTHTHTSHTSHTSHTHTHTSHTHTHTHTHTHTHTSHTSHTSHTSHTHTSHTSHTSHTHTSHTHTSHTHTSHTHTHTSHTSHTHTSHTSHTSHTSHTHTSHTHTHTSHTHTHTHTHTHTHTSHTSHTSHTSHTHTSHTSHTHTSHTSHTSHTHTSHTSHTSHTSHTHTSHTHTSHTHTHTHTHTSHTSHTSHTSHTHTSHTSHTSHTHTHTSHTSHTHTSHTSHTSHTSHTSHTSHTHTHTHTSHTHTSHTSHTSHTSHTSHTSHTHTHTHTSHTSHTSHTSHTSHTHTSHTHTHTSHTSHTHTHTSHTSHTHTHTHTHTSHTHTHTSHTSHTSHTSHTHTSHTSHTSHTSHTSHTHTSHTSHTHTHTHTHTHTSHTHTSHTSHTSHTHTHTHTHTSHTSHTHTHTHTSHTSHTHTHTHTSHTSHTSHTSHTHTHTHTHTHTSHTSHTSHTSHTSHTHTSHTSHTSHTSHTHTHTSHTSHTSHTSHTHTSHTSHTSHTHTHTHTSHTSHTSHTHTSHTSHTHTHTSHTSHTHTSHTHTHTSHTSHTHTHTSHTHTHTSHTHTSHTHTHTHTHTHTHTSHTSHTHTSHTHTSHTHTHTHTHTSHTHTSHTHTHTHTHTHTSHTHTHTHTSHTHTSHTSHTSHTHTHTSHTSHTHTSHTSHTHTHTHTSHTSHTHTHTSHTHTHTSHTHTHTSHTSHTSHTHTSHTSHTHTHTSHTHTHTSHTSHTSHTSHTSHTHTSHTSHTHTSHTSHTSHTSHTHTHTHTSHTSHTHTSHTSHTSHTHTHTSHTHTSHTSHTSHTSHTSHTSHTSHTHTSHTHTHTSHTHTHTSHTSHTSHTSHTHTSHTHTSHTHTHTSHTSHTHTHTHTSHTHTHTSHTSHTSHTSHTSHTHTSHTSHTSHTSHTHTHTHTSHTHTHTSHTHTHTSHTHTHTHTHTHTHTHTSHTSHTHTHTSHTSHTHTSHTSHTHTSHTHTHTSHTSHTHTSHTSHTSHTSHTSHTHTHTSHTSHTHTSHTSHTHTHTHTSHTSHTSHTHTHTHTHTSHTSHTHTSHTSHTSHTHTHTHTHTHTSHTHTHTSHTHTHTHTSHTHTSHTHTSHTHTHTSHTSHTHTSHTSHTSHTHTSHTHTHTHTHTHTSHTSHTHTSHTHTSHTHTHTHTSHTHTHTSHTSHTHTHTSHTHTHTHTSHTHTSHTSHTSHTHTHTHTSHTHTHTHTSHTSHTHTSHTSHTHTHTHTHTSHTSHTSHTHTHTHTSHTHTHTSHTSHTSHTSHTHTSHTHTSHTSHTSHTSHTHTSHTHTHTSHTHTHTSHTHTSHTHTHTSHTSHTSHTHTHTHTSHTSHTHTHTHTSHTSHTSHTHTSHTSHTHTHTHTSHTHTSHTHTHTSHTSHTSHTSHTSHTSHTHTHTSHTHTHTHTHTSHTSHTSHTSHTHTSHTSHTSHTHTHTSHTSHTHTHTSHTSHTHTHTSHTSHTHTHTHTHTHTHTHTSHTSHTHTHTHTSHTHTHTSHTHTSHTSHTHTSHTHTSHTHTSHTSHTSHTHTSHTSHTHTSHTHTSHTSHTHTSHTSHTSHTHTSHTSHTSHTSHTHTHTSHTSHTHTHTSHTHTSHTHTHTSHTHTSHTSHTSHTSHTHTHTSHTSHTSHTHTHTHTHTHTSHTSHTHTHTHTHTHTHTSHTHTSHTSHTHTSHTSHTSHTHTSHTSHTSHTHTSHTHTSHTSHTHTSHTSHTSHTHTSHTHTHTHTSHTSHTHTHTSHTSHTSHTHTSHTHTHTSHTHTHTSHTHTSHTSHTSHTSHTHTHTSHTHTSHTSHTHTSHTSHTSHTHTSHTHTHTSHTSHTSHTSHTHTHTHTHTHTSHTHTSHTHTHTSHTSHTHTSHTHTSHTSHTSHTSHTHTHTHTHTHTSHTHTSHTHTSHTHTHTSHTHTHTSHTHTSHTHTHTSHTSHTHTHTHTHTHTHTSHTSHTHTSHTHTHTSHTHTSHTHTHTSHTHTHTSHTHTHTHTSHTSHTHTSHTSHTHTSHTHTHTSHTHTHTHTSHTSHTHTHTSHTSHTHTSHTHTHTSHTHTSHTHTSHTHTHTHTHTHTHTHTHTSHTSHTSHTHTHTSHTHTSHTHTSHTSHTSHTSHTHTSHTSHTHTHTHTHTHTSHTSHTHTHTHTHTSHTHTHTSHSSWW"

    @compile_workload begin
        # All calls in this block will be precompiled, regardless of whether
        # they belong to your package or not (on Julia 1.8 and higher)
        try
            res = gridsynth(theta="pi/16", epsilon=1e-20)
            print(res)
        catch
            nothing
        end
        # These definitley improve TTFX. But the times were not terrible anyway.
        m = compose(gates_r1024)
        display(m[1,1])
        theta = big(pi)/1024
        get_theta(big(m)) - theta
        rot_mat_diff = big(m) - RZ(theta)
        opnorm(big(m) - RZ(theta))
        compose("TSH")
    end
end
